# Generated by Django 5.0 on 2023-12-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tecnologia', models.CharField(max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
